import { useParams, useNavigate, Link } from 'react-router-dom'
import { Button, EmptyState } from '../components/ui'
import { useStore, useCurrentUser, formatDate } from '../../data/store'
import { COMPANY } from '../../data/company'
import { RESULT_LABELS, resultTone, isOverdue } from '../../data/ga1'

export default function GA1Detail() {
  const { id } = useParams()
  const nav = useNavigate()
  const { state, dispatch } = useStore()
  const { can } = useCurrentUser()

  const g = state.ga1.find((x) => x.id === id)
  if (!g) {
    return (
      <div>
        <Link className="back-link" to="/ga1">← GA1 Inspections</Link>
        <div className="card"><EmptyState title="Inspection not found" hint="It may have been removed." /></div>
      </div>
    )
  }

  const canManage = can('create:records')
  const client = state.clients.find((c) => c.id === g.clientId)
  const examiner = state.employees.find((e) => e.id === g.examinerId)
  const overdue = isOverdue(g.nextExaminationDate)

  const remove = () => {
    if (confirm(`Delete inspection ${g.reportNumber}?`)) {
      dispatch({ type: 'REMOVE_GA1', id: g.id })
      nav('/ga1')
    }
  }
  const emailReport = () => {
    const subject = `GA1 Inspection ${g.reportNumber} — ${COMPANY.name}`
    const body =
      `Hi ${client?.name ?? ''},\n\n` +
      `Please find GA1 thorough-examination report ${g.reportNumber} for ${g.equipmentType} ` +
      `(${[g.manufacturer, g.model].filter(Boolean).join(' ')}).\n` +
      `Result: ${RESULT_LABELS[g.overallResult]}. Next examination due ${formatDate(g.nextExaminationDate)}.\n\n` +
      `Kind regards,\n${COMPANY.name}`
    window.location.href = `mailto:${client?.email ?? ''}?subject=${encodeURIComponent(subject)}&body=${encodeURIComponent(body)}`
  }

  return (
    <div>
      <Link className="back-link" to="/ga1">← GA1 Inspections</Link>

      <div className="detail-head">
        <div className="detail-id">
          <div>
            <h1 className="detail-name">{g.reportNumber}</h1>
            <div className="detail-sub">
              {client && <Link className="link" to={`/clients/${client.id}`}>{client.name}</Link>}
              <span className={`badge badge-${resultTone[g.overallResult]}`}>{RESULT_LABELS[g.overallResult]}</span>
              {g.safeToUse && <span className="badge badge-green">Safe to use</span>}
              {g.defectsFound && <span className="badge badge-red">Defects found</span>}
            </div>
          </div>
        </div>
        <div className="detail-actions">
          {/* PDF is generated by a serverless function (Phase B). */}
          <a href={`/api/ga1/${g.id}/pdf`} target="_blank" rel="noreferrer">
            <Button variant="secondary">Download PDF</Button>
          </a>
          <Button variant="secondary" onClick={emailReport}>Email</Button>
          {canManage && (
            <>
              <Button variant="secondary" onClick={() => nav(`/ga1/${g.id}/edit`)}>Edit</Button>
              <Button variant="danger" onClick={remove}>Delete</Button>
            </>
          )}
        </div>
      </div>

      {overdue && (
        <div className="ga1-alert">
          Next examination was due {formatDate(g.nextExaminationDate)} — this is overdue.
        </div>
      )}

      <div className="detail-grid">
        <div className="card contact-card">
          <div className="contact-row"><span>Client</span><strong>{client?.company || client?.name || '—'}</strong></div>
          <div className="contact-row"><span>Site</span><strong>{g.examinationLocation || '—'}</strong></div>
          <div className="contact-row"><span>Competent person</span><strong>{examiner?.name ?? '—'}</strong></div>
          <div className="contact-row"><span>Cert no.</span><strong>{g.examinerCert || '—'}</strong></div>
          <div className="contact-row"><span>Purpose</span><strong>{g.purposeOfExamination || '—'}</strong></div>
        </div>
        <div className="card contact-card">
          <div className="contact-row"><span>Equipment</span><strong>{g.equipmentType || '—'}</strong></div>
          <div className="contact-row"><span>Manufacturer</span><strong>{g.manufacturer || '—'}</strong></div>
          <div className="contact-row"><span>Model</span><strong>{g.model || '—'}</strong></div>
          <div className="contact-row"><span>Serial no.</span><strong>{g.serialNumber || '—'}</strong></div>
          <div className="contact-row"><span>SWL / WLL</span><strong>{g.swl || '—'}</strong></div>
        </div>
      </div>

      <div className="detail-section">
        <div className="detail-section-title">Examination timeline</div>
        <div className="card">
          <div className="ga1-timeline">
            <div><span className="doc-label">Examined</span><strong>{formatDate(g.examinationDate)}</strong></div>
            <div><span className="doc-label">Previous</span><strong>{formatDate(g.previousExaminationDate)}</strong></div>
            <div><span className="doc-label">Next due</span><strong className={overdue ? 'ga1-overdue' : ''}>{formatDate(g.nextExaminationDate)}</strong></div>
            <div><span className="doc-label">Year of mfr.</span><strong>{g.yearOfManufacture || '—'}</strong></div>
          </div>
        </div>
      </div>

      {(g.defectsDescription || g.reinspectionDate || g.additionalNotes || g.particularsOfTests) && (
        <div className="detail-section">
          <div className="detail-section-title">Findings</div>
          <div className="card ga1-findings">
            {g.particularsOfTests && <div><div className="doc-label">Particulars of tests</div><p>{g.particularsOfTests}</p></div>}
            {g.defectsDescription && <div><div className="doc-label">Defects / actions required</div><p>{g.defectsDescription}</p></div>}
            {g.reinspectionDate && <div className="ga1-reinspect">Re-inspection / repair required by {formatDate(g.reinspectionDate)}</div>}
            {g.additionalNotes && <div><div className="doc-label">Additional notes</div><p>{g.additionalNotes}</p></div>}
          </div>
        </div>
      )}

      {g.signature && (
        <div className="detail-section">
          <div className="detail-section-title">Examiner signature</div>
          <div className="card ga1-signature">
            <span className="ga1-sig">{g.signature}</span>
            {examiner && <span className="cell-muted">{examiner.name}</span>}
          </div>
        </div>
      )}
    </div>
  )
}
