import { useParams, useNavigate } from 'react-router-dom'
import { useStore, useCurrentUser, formatDate } from '../data/store'
import { RESULT_LABELS, resultTone } from '../data/ga1'
import FieldPhotos from './FieldPhotos'
import './screens.css'
import './field.css'
import './JobView.css'

export default function FieldGA1Detail() {
  const { id } = useParams()
  const nav = useNavigate()
  const { state } = useStore()
  const { can } = useCurrentUser()

  const g = state.ga1.find((x) => x.id === id)
  if (!g) {
    return (
      <div>
        <div className="fld-topbar"><div className="fld-topbar-left"><button className="fld-back" onClick={() => nav(-1)}>←</button><span>Inspection</span></div></div>
        <div className="placeholder"><h2>Not found</h2></div>
      </div>
    )
  }

  const client = state.clients.find((c) => c.id === g.clientId)
  const examiner = state.employees.find((e) => e.id === g.examinerId)

  return (
    <div>
      <div className="fld-topbar">
        <div className="fld-topbar-left">
          <button className="fld-back" onClick={() => nav(-1)}>←</button>
          <span>{g.reportNumber}</span>
        </div>
        {can('view:ga1') && <button className="fld-topbar-btn" onClick={() => nav(`/field/ga1/${g.id}/edit`)}>Edit</button>}
      </div>

      <div className="pad">
        <div className="fld-job-status" style={{ marginBottom: 14 }}>
          <span className={`badge badge-${resultTone[g.overallResult]}`}>{RESULT_LABELS[g.overallResult]}</span>
        </div>

        <div className="fld-card">
          <div className="fld-row"><span>Client</span><strong>{client?.name ?? '—'}</strong></div>
          <div className="fld-row"><span>Equipment</span><strong>{g.equipmentType || '—'}</strong></div>
          <div className="fld-row"><span>Make / model</span><strong>{[g.manufacturer, g.model].filter(Boolean).join(' ') || '—'}</strong></div>
          <div className="fld-row"><span>Serial</span><strong>{g.serialNumber || '—'}</strong></div>
          <div className="fld-row"><span>SWL</span><strong>{g.swl || '—'}</strong></div>
          <div className="fld-row"><span>Examiner</span><strong>{examiner?.name ?? '—'}</strong></div>
          <div className="fld-row"><span>Examined</span><strong>{formatDate(g.examinationDate)}</strong></div>
          <div className="fld-row"><span>Next due</span><strong>{formatDate(g.nextExaminationDate)}</strong></div>
        </div>

        {g.defectsDescription && (
          <>
            <h3 className="fld-h3">Defects / actions</h3>
            <div className="fld-card"><div className="fld-row"><span style={{ whiteSpace: 'normal' }}>{g.defectsDescription}</span></div></div>
          </>
        )}

        <h3 className="fld-h3">Photos</h3>
        <FieldPhotos entityType="ga1" entityId={g.id} />

        {/* PDF is generated by the serverless endpoint (works on the deployed site). */}
        <a className="fld-pdf-btn" href={`/api/ga1/${g.id}/pdf`} target="_blank" rel="noreferrer" style={{ marginTop: 20 }}>Download PDF certificate</a>
      </div>
    </div>
  )
}
